defaults.url=https://sentry.io/
auth.token=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

# Optional if you're using env vars for these already:
# defaults.org=your-org-slug
# defaults.project=your-project-slug 