import mongoose, { Schema, Document } from 'mongoose';

export interface IPost extends Document {
  userId: string;
  videoId: string;
  platform: 'instagram' | 'tiktok' | 'facebook' | 'youtube';
  content: string; // Caption
  hashtags: string[];
  status: 'scheduled' | 'posted' | 'failed' | 'cancelled';
  scheduledTime: Date;
  postedTime?: Date;
  autoGenerated: boolean;
  contentType: 'video' | 'image';
  engagementMetrics?: {
    likes: number;
    comments: number;
    shares: number;
    views: number;
    reach: number;
    impressions: number;
  };
  errorMessage?: string;
  retryCount: number;
  musicUsed?: string;
  thumbnailUsed?: string;
  createdAt: Date;
  updatedAt: Date;
}

const postSchema = new Schema<IPost>({
  userId: {
    type: String,
    required: true,
    ref: 'User'
  },
  videoId: {
    type: String,
    required: true,
    ref: 'Video'
  },
  platform: {
    type: String,
    enum: ['instagram', 'tiktok', 'facebook'],
    required: true
  },
  content: {
    type: String,
    required: true
  },
  hashtags: [String],
  status: {
    type: String,
    enum: ['scheduled', 'posted', 'failed', 'cancelled'],
    default: 'scheduled'
  },
  scheduledTime: {
    type: Date,
    required: true
  },
  postedTime: Date,
  autoGenerated: {
    type: Boolean,
    default: false
  },
  contentType: {
    type: String,
    enum: ['video', 'image'],
    required: true
  },
  engagementMetrics: {
    likes: { type: Number, default: 0 },
    comments: { type: Number, default: 0 },
    shares: { type: Number, default: 0 },
    views: { type: Number, default: 0 },
    reach: { type: Number, default: 0 },
    impressions: { type: Number, default: 0 }
  },
  errorMessage: String,
  retryCount: {
    type: Number,
    default: 0
  },
  musicUsed: String,
  thumbnailUsed: String
}, {
  timestamps: true
});

// Create indexes
postSchema.index({ userId: 1 });
postSchema.index({ videoId: 1 });
postSchema.index({ platform: 1 });
postSchema.index({ status: 1 });
postSchema.index({ scheduledTime: 1 });

export const Post = mongoose.model<IPost>('Post', postSchema);

// Export model alias for service compatibility  
export const PostModel = Post;

// Export interfaces for backward compatibility
export interface PostCreateInput {
  userId: string;
  videoId: string;
  platform: 'instagram' | 'tiktok' | 'facebook';
  content: string;
  hashtags: string[];
  scheduledTime: Date;
  autoGenerated: boolean;
  contentType: 'video' | 'image';
  musicUsed?: string;
  thumbnailUsed?: string;
}

export interface PostUpdateInput {
  content?: string;
  hashtags?: string[];
  status?: 'scheduled' | 'posted' | 'failed' | 'cancelled';
  scheduledTime?: Date;
  postedTime?: Date;
  engagementMetrics?: {
    likes?: number;
    comments?: number;
    shares?: number;
    views?: number;
    reach?: number;
    impressions?: number;
  };
  errorMessage?: string;
  retryCount?: number;
  musicUsed?: string;
  thumbnailUsed?: string;
} 