import { Pool } from 'pg';

export interface Post {
  id: string;
  userId: string;
  videoId: string;
  platform: 'instagram' | 'tiktok' | 'facebook';
  content: string; // Caption
  hashtags: string[];
  status: 'scheduled' | 'posted' | 'failed' | 'cancelled';
  scheduledTime: Date;
  postedTime?: Date;
  autoGenerated: boolean;
  contentType: 'video' | 'image';
  engagementMetrics?: {
    likes: number;
    comments: number;
    shares: number;
    views: number;
    reach: number;
    impressions: number;
  };
  errorMessage?: string;
  retryCount: number;
  musicUsed?: string;
  thumbnailUsed?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface PostCreateInput {
  userId: string;
  videoId: string;
  platform: 'instagram' | 'tiktok' | 'facebook';
  content: string;
  hashtags: string[];
  scheduledTime: Date;
  autoGenerated: boolean;
  contentType: 'video' | 'image';
  musicUsed?: string;
  thumbnailUsed?: string;
}

export interface PostUpdateInput {
  content?: string;
  hashtags?: string[];
  status?: 'scheduled' | 'posted' | 'failed' | 'cancelled';
  scheduledTime?: Date;
  postedTime?: Date;
  engagementMetrics?: {
    likes: number;
    comments: number;
    shares: number;
    views: number;
    reach: number;
    impressions: number;
  };
  errorMessage?: string;
  retryCount?: number;
  musicUsed?: string;
  thumbnailUsed?: string;
}

export class PostModel {
  private pool: Pool;

  constructor(pool: Pool) {
    this.pool = pool;
  }

  async create(input: PostCreateInput): Promise<Post> {
    const query = `
      INSERT INTO posts (
        user_id, video_id, platform, content, hashtags, status,
        scheduled_time, auto_generated, content_type, music_used,
        thumbnail_used, retry_count, created_at, updated_at
      )
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW(), NOW())
      RETURNING *
    `;

    const values = [
      input.userId,
      input.videoId,
      input.platform,
      input.content,
      JSON.stringify(input.hashtags),
      'scheduled',
      input.scheduledTime,
      input.autoGenerated,
      input.contentType,
      input.musicUsed,
      input.thumbnailUsed,
      0 // retryCount starts at 0
    ];

    const result = await this.pool.query(query, values);
    return this.mapRowToPost(result.rows[0]);
  }

  async findById(id: string): Promise<Post | null> {
    const query = 'SELECT * FROM posts WHERE id = $1';
    const result = await this.pool.query(query, [id]);
    
    if (result.rows.length === 0) return null;
    return this.mapRowToPost(result.rows[0]);
  }

  async findByUser(userId: string, options?: {
    status?: 'scheduled' | 'posted' | 'failed' | 'cancelled';
    platform?: 'instagram' | 'tiktok' | 'facebook';
    limit?: number;
    offset?: number;
    startDate?: Date;
    endDate?: Date;
  }): Promise<Post[]> {
    let query = 'SELECT * FROM posts WHERE user_id = $1';
    const values: any[] = [userId];
    let paramCount = 1;

    if (options?.status) {
      paramCount++;
      query += ` AND status = $${paramCount}`;
      values.push(options.status);
    }

    if (options?.platform) {
      paramCount++;
      query += ` AND platform = $${paramCount}`;
      values.push(options.platform);
    }

    if (options?.startDate) {
      paramCount++;
      query += ` AND scheduled_time >= $${paramCount}`;
      values.push(options.startDate);
    }

    if (options?.endDate) {
      paramCount++;
      query += ` AND scheduled_time <= $${paramCount}`;
      values.push(options.endDate);
    }

    query += ' ORDER BY scheduled_time DESC';

    if (options?.limit) {
      paramCount++;
      query += ` LIMIT $${paramCount}`;
      values.push(options.limit);
    }

    if (options?.offset) {
      paramCount++;
      query += ` OFFSET $${paramCount}`;
      values.push(options.offset);
    }

    const result = await this.pool.query(query, values);
    return result.rows.map(row => this.mapRowToPost(row));
  }

  async getScheduledPosts(userId: string, startDate: Date, endDate: Date): Promise<Post[]> {
    const query = `
      SELECT * FROM posts 
      WHERE user_id = $1 
        AND status = 'scheduled'
        AND scheduled_time BETWEEN $2 AND $3
      ORDER BY scheduled_time ASC
    `;

    const result = await this.pool.query(query, [userId, startDate, endDate]);
    return result.rows.map(row => this.mapRowToPost(row));
  }

  async markAsPosted(id: string, engagementMetrics?: {
    likes: number;
    comments: number;
    shares: number;
    views: number;
    reach: number;
    impressions: number;
  }): Promise<Post | null> {
    const query = `
      UPDATE posts 
      SET 
        status = 'posted',
        posted_time = NOW(),
        engagement_metrics = $1,
        updated_at = NOW()
      WHERE id = $2
      RETURNING *
    `;

    const result = await this.pool.query(query, [
      engagementMetrics ? JSON.stringify(engagementMetrics) : null,
      id
    ]);
    
    if (result.rows.length === 0) return null;
    return this.mapRowToPost(result.rows[0]);
  }

  async markAsFailed(id: string, errorMessage: string): Promise<Post | null> {
    const query = `
      UPDATE posts 
      SET 
        status = 'failed',
        error_message = $1,
        retry_count = retry_count + 1,
        updated_at = NOW()
      WHERE id = $2
      RETURNING *
    `;

    const result = await this.pool.query(query, [errorMessage, id]);
    
    if (result.rows.length === 0) return null;
    return this.mapRowToPost(result.rows[0]);
  }

  async update(id: string, input: PostUpdateInput): Promise<Post | null> {
    const fields: string[] = [];
    const values: any[] = [];
    let paramCount = 1;

    Object.entries(input).forEach(([key, value]) => {
      if (value !== undefined) {
        const dbField = this.camelToSnake(key);
        if (key === 'hashtags' || key === 'engagementMetrics') {
          fields.push(`${dbField} = $${paramCount}`);
          values.push(JSON.stringify(value));
        } else {
          fields.push(`${dbField} = $${paramCount}`);
          values.push(value);
        }
        paramCount++;
      }
    });

    if (fields.length === 0) return this.findById(id);

    fields.push(`updated_at = NOW()`);
    values.push(id);

    const query = `
      UPDATE posts 
      SET ${fields.join(', ')}
      WHERE id = $${paramCount}
      RETURNING *
    `;

    const result = await this.pool.query(query, values);
    
    if (result.rows.length === 0) return null;
    return this.mapRowToPost(result.rows[0]);
  }

  async getPostingStats(userId: string, days: number = 30): Promise<{
    totalPosts: number;
    successfulPosts: number;
    failedPosts: number;
    scheduledPosts: number;
    totalEngagement: {
      likes: number;
      comments: number;
      shares: number;
      views: number;
      reach: number;
      impressions: number;
    };
    avgEngagement: {
      likes: number;
      comments: number;
      shares: number;
      views: number;
      reach: number;
      impressions: number;
    };
    byPlatform: {
      instagram: number;
      tiktok: number;
      facebook: number;
    };
  }> {
    const startDate = new Date();
    startDate.setDate(startDate.getDate() - days);

    const query = `
      SELECT 
        COUNT(*) as total_posts,
        COUNT(CASE WHEN status = 'posted' THEN 1 END) as successful_posts,
        COUNT(CASE WHEN status = 'failed' THEN 1 END) as failed_posts,
        COUNT(CASE WHEN status = 'scheduled' THEN 1 END) as scheduled_posts,
        SUM(COALESCE(engagement_metrics->>'likes', '0')::int) as total_likes,
        SUM(COALESCE(engagement_metrics->>'comments', '0')::int) as total_comments,
        SUM(COALESCE(engagement_metrics->>'shares', '0')::int) as total_shares,
        SUM(COALESCE(engagement_metrics->>'views', '0')::int) as total_views,
        SUM(COALESCE(engagement_metrics->>'reach', '0')::int) as total_reach,
        SUM(COALESCE(engagement_metrics->>'impressions', '0')::int) as total_impressions,
        COUNT(CASE WHEN platform = 'instagram' THEN 1 END) as instagram_posts,
        COUNT(CASE WHEN platform = 'tiktok' THEN 1 END) as tiktok_posts,
        COUNT(CASE WHEN platform = 'facebook' THEN 1 END) as facebook_posts
      FROM posts 
      WHERE user_id = $1 AND created_at >= $2
    `;

    const result = await this.pool.query(query, [userId, startDate]);
    const row = result.rows[0];

    const successfulPosts = parseInt(row.successful_posts) || 0;

    return {
      totalPosts: parseInt(row.total_posts) || 0,
      successfulPosts,
      failedPosts: parseInt(row.failed_posts) || 0,
      scheduledPosts: parseInt(row.scheduled_posts) || 0,
      totalEngagement: {
        likes: parseInt(row.total_likes) || 0,
        comments: parseInt(row.total_comments) || 0,
        shares: parseInt(row.total_shares) || 0,
        views: parseInt(row.total_views) || 0,
        reach: parseInt(row.total_reach) || 0,
        impressions: parseInt(row.total_impressions) || 0
      },
      avgEngagement: {
        likes: successfulPosts > 0 ? Math.round(parseInt(row.total_likes) / successfulPosts) : 0,
        comments: successfulPosts > 0 ? Math.round(parseInt(row.total_comments) / successfulPosts) : 0,
        shares: successfulPosts > 0 ? Math.round(parseInt(row.total_shares) / successfulPosts) : 0,
        views: successfulPosts > 0 ? Math.round(parseInt(row.total_views) / successfulPosts) : 0,
        reach: successfulPosts > 0 ? Math.round(parseInt(row.total_reach) / successfulPosts) : 0,
        impressions: successfulPosts > 0 ? Math.round(parseInt(row.total_impressions) / successfulPosts) : 0
      },
      byPlatform: {
        instagram: parseInt(row.instagram_posts) || 0,
        tiktok: parseInt(row.tiktok_posts) || 0,
        facebook: parseInt(row.facebook_posts) || 0
      }
    };
  }

  async getFailedPostsForRetry(userId: string, maxRetries: number = 3): Promise<Post[]> {
    const query = `
      SELECT * FROM posts 
      WHERE user_id = $1 
        AND status = 'failed'
        AND retry_count < $2
        AND scheduled_time > NOW() - INTERVAL '24 hours'
      ORDER BY scheduled_time ASC
    `;

    const result = await this.pool.query(query, [userId, maxRetries]);
    return result.rows.map(row => this.mapRowToPost(row));
  }

  private mapRowToPost(row: any): Post {
    return {
      id: row.id,
      userId: row.user_id,
      videoId: row.video_id,
      platform: row.platform,
      content: row.content,
      hashtags: JSON.parse(row.hashtags || '[]'),
      status: row.status,
      scheduledTime: new Date(row.scheduled_time),
      postedTime: row.posted_time ? new Date(row.posted_time) : undefined as any,
      autoGenerated: row.auto_generated,
      contentType: row.content_type,
      engagementMetrics: row.engagement_metrics ? JSON.parse(row.engagement_metrics) : undefined,
      errorMessage: row.error_message,
      retryCount: parseInt(row.retry_count),
      musicUsed: row.music_used,
      thumbnailUsed: row.thumbnail_used,
      createdAt: new Date(row.created_at),
      updatedAt: new Date(row.updated_at)
    };
  }

  private camelToSnake(str: string): string {
    return str.replace(/[A-Z]/g, letter => `_${letter.toLowerCase()}`);
  }
} 