// Unified type definitions to resolve conflicts across the project
// This file serves as the single source of truth for shared types

// ========================================
// Core Entity Types (Unified)
// ========================================

// Unified User interface (resolves conflicts between different User definitions)
export interface UnifiedUser {
  id: string | number; // Support both string and number IDs
  email: string;
  name: string;
  password?: string; // Optional for API responses
  company?: string;
  phone?: string;
  avatarUrl?: string;
  username?: string;
  autoPostingEnabled: boolean;
  cameraRollPath?: string;
  postingTimes?: string | string[]; // Support both JSON string and array
  subscriptionTier?: SubscriptionTier;
  subscriptionExpiresAt?: Date;
  testMode?: boolean;
  socialAccounts?: SocialAccountConnections;
  createdAt: Date | string;
  updatedAt?: Date | string;
}

// Unified Video interface (resolves conflicts between different Video definitions)
export interface UnifiedVideo {
  id: string | number;
  userId: string | number;
  title: string;
  description?: string;
  filename?: string;
  fileName?: string; // Support both naming conventions
  filePath?: string;
  fileUrl?: string;
  thumbnailUrl?: string;
  thumbnailPath?: string;
  duration: number; // in seconds
  fileSize: number; // in bytes
  resolution?: string;
  hasAudio?: boolean;
  mimeType?: string;
  category: VideoCategory;
  propertyType?: string;
  location?: string;
  price?: number;
  tags: string[] | string; // Support both array and JSON string
  aiScore?: number;
  status: VideoStatus;
  postCount: number;
  lastPosted?: Date | string;
  lastPostedAt?: Date | string;
  isActive: boolean;
  nextPostDate?: Date | string;
  preferredCaption?: string;
  preferredHashtags?: string[] | string;
  preferredMusic?: string;
  coolOffDays: number;
  metadata?: VideoMetadata;
  processing?: VideoProcessingStatus;
  optimization?: VideoOptimization;
  createdAt: Date | string;
  updatedAt?: Date | string;
}

// Unified Post interface (resolves conflicts between different Post definitions)
export interface UnifiedPost {
  id: string | number;
  userId: string | number;
  videoId: string | number;
  platform: SocialPlatform;
  platformPostId?: string;
  content?: string;
  caption?: string; // Support both content and caption
  hashtags: string[] | string;
  scheduledTime?: Date | string;
  scheduledAt?: Date | string;
  postedTime?: Date | string;
  postedAt?: Date | string;
  status: PostStatus;
  engagement?: string | EngagementData;
  engagementRate?: number;
  engagementData?: EngagementData;
  impressions?: number;
  reach?: number;
  errorMessage?: string;
  retryCount: number;
  maxRetries?: number;
  autoGenerated?: boolean;
  contentType?: ContentType;
  musicUsed?: string;
  thumbnailUsed?: string;
  optimization?: PostOptimization;
  createdAt: Date | string;
  updatedAt?: Date | string;
}

// ========================================
// Shared Enums and Constants
// ========================================

export enum SubscriptionTier {
  FREE = 'free',
  BASIC = 'basic',
  PRO = 'pro',
  ENTERPRISE = 'enterprise'
}

export enum VideoCategory {
  REAL_ESTATE = 'real-estate',
  CARTOON = 'cartoon',
  GENERAL = 'general'
}

export enum VideoStatus {
  PROCESSING = 'processing',
  READY = 'ready',
  FAILED = 'failed',
  UPLOADING = 'uploading'
}

export enum PostStatus {
  SCHEDULED = 'scheduled',
  POSTED = 'posted',
  FAILED = 'failed',
  CANCELLED = 'cancelled',
  DRAFT = 'draft'
}

export enum SocialPlatform {
  INSTAGRAM = 'instagram',
  TIKTOK = 'tiktok',
  YOUTUBE = 'youtube',
  FACEBOOK = 'facebook',
  TWITTER = 'twitter'
}

export enum ContentType {
  VIDEO = 'video',
  IMAGE = 'image',
  STORY = 'story',
  REEL = 'reel',
  SHORT = 'short'
}

// ========================================
// Supporting Interfaces
// ========================================

export interface SocialAccountConnections {
  instagram?: SocialAccountConnection;
  tiktok?: SocialAccountConnection;
  youtube?: SocialAccountConnection;
  facebook?: SocialAccountConnection;
  twitter?: SocialAccountConnection;
}

export interface SocialAccountConnection {
  connected: boolean;
  username?: string;
  accessToken?: string;
  refreshToken?: string;
  expiresAt?: Date | string;
  lastSync?: Date | string;
  syncStatus?: string;
}

export interface VideoMetadata {
  duration: number;
  resolution: {
    width: number;
    height: number;
  };
  fps?: number;
  bitrate?: number;
  codec?: string;
  hasAudio: boolean;
  audioCodec?: string;
  fileSize: number;
  isVertical?: boolean;
  quality?: 'low' | 'medium' | 'high' | 'ultra';
}

export interface VideoProcessingStatus {
  status: 'pending' | 'processing' | 'completed' | 'failed';
  progress: number; // 0-100
  currentStep?: string;
  errorMessage?: string;
  startedAt?: Date;
  completedAt?: Date;
}

export interface VideoOptimization {
  thumbnailGenerated: boolean;
  audioAnalyzed: boolean;
  sceneAnalyzed: boolean;
  qualityScore: number;
  recommendations: string[];
}

export interface EngagementData {
  likes: number;
  comments: number;
  shares: number;
  views: number;
  saves?: number;
  reach?: number;
  impressions?: number;
  engagementRate?: number;
}

export interface PostOptimization {
  captionOptimized: boolean;
  hashtagsOptimized: boolean;
  timingOptimized: boolean;
  thumbnailOptimized: boolean;
  score: number;
}

// ========================================
// API Response Types
// ========================================

export interface ApiResponse<T = any> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
  timestamp: string;
}

export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    pages: number;
    hasNext: boolean;
    hasPrev: boolean;
  };
}

// ========================================
// Database Query Types
// ========================================

export interface QueryResult<T> {
  rows: T[];
  rowCount: number;
}

export interface QueryOptions {
  limit?: number;
  offset?: number;
  orderBy?: string;
  orderDirection?: 'ASC' | 'DESC';
  filters?: Record<string, any>;
}

// ========================================
// Type Conversion Utilities
// ========================================

/**
 * Convert database user to unified user format
 */
export function toUnifiedUser(dbUser: any): UnifiedUser {
  return {
    id: dbUser.id,
    email: dbUser.email,
    name: dbUser.name,
    username: dbUser.username,
    autoPostingEnabled: Boolean(dbUser.autoPostingEnabled || dbUser.auto_posting_enabled),
    cameraRollPath: dbUser.cameraRollPath || dbUser.camera_roll_path,
    postingTimes: dbUser.postingTimes || dbUser.posting_times,
    testMode: Boolean(dbUser.testMode || dbUser.test_mode),
    createdAt: new Date(dbUser.createdAt || dbUser.created_at),
    updatedAt: dbUser.updatedAt ? new Date(dbUser.updatedAt || dbUser.updated_at) : undefined,
  };
}

/**
 * Convert database video to unified video format
 */
export function toUnifiedVideo(dbVideo: any): UnifiedVideo {
  return {
    id: dbVideo.id,
    userId: dbVideo.userId || dbVideo.user_id,
    title: dbVideo.title,
    description: dbVideo.description,
    filename: dbVideo.filename || dbVideo.fileName,
    filePath: dbVideo.filePath || dbVideo.file_path,
    fileUrl: dbVideo.fileUrl || dbVideo.file_url,
    thumbnailPath: dbVideo.thumbnailPath || dbVideo.thumbnail_path,
    duration: Number(dbVideo.duration || 0),
    fileSize: Number(dbVideo.fileSize || dbVideo.file_size || 0),
    resolution: dbVideo.resolution,
    hasAudio: Boolean(dbVideo.hasAudio || dbVideo.has_audio),
    category: dbVideo.category as VideoCategory,
    propertyType: dbVideo.propertyType || dbVideo.property_type,
    location: dbVideo.location,
    price: dbVideo.price ? Number(dbVideo.price) : undefined,
    tags: typeof dbVideo.tags === 'string' ? JSON.parse(dbVideo.tags) : dbVideo.tags || [],
    aiScore: dbVideo.aiScore || dbVideo.ai_score,
    status: dbVideo.status as VideoStatus,
    postCount: Number(dbVideo.postCount || dbVideo.post_count || 0),
    lastPosted: dbVideo.lastPosted ? new Date(dbVideo.lastPosted || dbVideo.last_posted) : undefined,
    isActive: Boolean(dbVideo.isActive !== undefined ? dbVideo.isActive : dbVideo.is_active),
    nextPostDate: dbVideo.nextPostDate ? new Date(dbVideo.nextPostDate || dbVideo.next_post_date) : undefined,
    preferredCaption: dbVideo.preferredCaption || dbVideo.preferred_caption,
    preferredHashtags: dbVideo.preferredHashtags || dbVideo.preferred_hashtags,
    preferredMusic: dbVideo.preferredMusic || dbVideo.preferred_music,
    coolOffDays: Number(dbVideo.coolOffDays || dbVideo.cool_off_days || 30),
    createdAt: new Date(dbVideo.createdAt || dbVideo.created_at),
    updatedAt: dbVideo.updatedAt ? new Date(dbVideo.updatedAt || dbVideo.updated_at) : undefined,
  };
}

/**
 * Convert database post to unified post format
 */
export function toUnifiedPost(dbPost: any): UnifiedPost {
  return {
    id: dbPost.id,
    userId: dbPost.userId || dbPost.user_id,
    videoId: dbPost.videoId || dbPost.video_id,
    platform: dbPost.platform as SocialPlatform,
    platformPostId: dbPost.platformPostId || dbPost.platform_post_id,
    content: dbPost.content || dbPost.caption,
    hashtags: typeof dbPost.hashtags === 'string' ? JSON.parse(dbPost.hashtags) : dbPost.hashtags || [],
    scheduledTime: dbPost.scheduledTime ? new Date(dbPost.scheduledTime || dbPost.scheduled_time) : undefined,
    postedTime: dbPost.postedTime ? new Date(dbPost.postedTime || dbPost.posted_time) : undefined,
    status: dbPost.status as PostStatus,
    engagement: dbPost.engagement,
    engagementRate: dbPost.engagementRate || dbPost.engagement_rate,
    impressions: dbPost.impressions,
    reach: dbPost.reach,
    errorMessage: dbPost.errorMessage || dbPost.error_message,
    retryCount: Number(dbPost.retryCount || dbPost.retry_count || 0),
    createdAt: new Date(dbPost.createdAt || dbPost.created_at),
    updatedAt: dbPost.updatedAt ? new Date(dbPost.updatedAt || dbPost.updated_at) : undefined,
  };
}

// ========================================
// Export specific types from other files (to avoid conflicts)
// ========================================

// Re-export specific types that don't conflict with unified types
export type { User as OriginalUser, UserSettings, UsageStats, CaptionTone } from './user';
export type { Video as OriginalVideo } from './video';
export type { Post as OriginalPost } from './post';
export type { DatabaseUser, DatabaseVideo, DatabasePost, QueryResult as DatabaseQueryResult } from './database'; 