import { logger } from '../utils/logger';
import User from '../models/User';
import { Video } from '../models/Video';
import { Post } from '../models/Post';
import { InstagramService } from './instagramService';
import { CaptionGenerationService } from './captionGenerationService';
import { AnalyticsService } from './analyticsService';

export interface PostingSchedule {
  userId: string;
  times: string[];
  days: number[];
  categoryRotation: string[];
  postsPerDay: number;
  timezone: string;
}

export interface PostingResult {
  success: boolean;
  postId?: string;
  error?: string;
  engagementMetrics?: any;
  scheduledTime: Date;
  videoId: string;
  platform: string;
}

export interface SmartPostingOptions {
  useEngagementData?: boolean;
  avoidDuplicateContent?: boolean;
  optimizeTiming?: boolean;
}

export class AutoPostingService {
  private userModel: typeof User;
  private videoModel: typeof Video;
  private postModel: typeof Post;
  private instagramService: InstagramService;
  private captionService: CaptionGenerationService;
  private analyticsService: AnalyticsService;

  constructor() {
    this.userModel = User;
    this.videoModel = Video;
    this.postModel = Post;
    this.instagramService = new InstagramService();
    this.captionService = new CaptionGenerationService();
    this.analyticsService = new AnalyticsService();
  }

  /**
   * Schedule posts for a user based on their settings
   */
  async schedulePosts(userId: string, days: number = 7): Promise<PostingResult[]> {
    try {
      logger.info(`Scheduling posts for user ${userId} for ${days} days`);

      const user = await this.userModel.findById(userId);
      if (!user || !user.autoPostingEnabled) {
        throw new Error('User not found or auto-posting disabled');
      }

      const schedule: PostingSchedule = {
        userId,
        times: user.postingTimes || ['09:00', '13:00', '18:00'],
        days: [1, 2, 3, 4, 5, 6, 7], // All days
        categoryRotation: ['real-estate', 'cartoon'],
        postsPerDay: 3,
        timezone: user.timezone || 'America/Chicago',
      };

      const results: PostingResult[] = [];
      const startDate = new Date();

      for (let day = 0; day < days; day++) {
        const currentDate = new Date(startDate);
        currentDate.setDate(currentDate.getDate() + day);

        for (let postIndex = 0; postIndex < schedule.postsPerDay; postIndex++) {
          const category = schedule.categoryRotation[postIndex % schedule.categoryRotation.length];
          const postingTime = schedule.times[postIndex % schedule.times.length];

          const result = await this.scheduleSinglePost(userId, {
            date: currentDate,
            time: postingTime || '09:00',
            category: category || 'real-estate',
            timezone: schedule.timezone,
          });

          results.push(result);
        }
      }

      logger.info(`Scheduled ${results.length} posts for user ${userId}`);
      return results;
    } catch (error) {
      logger.error('Failed to schedule posts:', error);
      throw error;
    }
  }

  /**
   * Schedule a single post
   */
  private async scheduleSinglePost(
    userId: string,
    options: {
      date: Date;
      time: string;
      category: string;
      timezone: string;
    }
  ): Promise<PostingResult> {
    try {
      // Get next available video
      const video = await this.videoModel
        .findOne({
          userId,
          isActive: true,
          category: options.category || 'real-estate',
          $or: [{ nextPostDate: { $lte: new Date() } }, { nextPostDate: null }],
        })
        .sort({ lastPostedAt: 1 });

      if (!video) {
        return {
          success: false,
          error: `No videos available for category: ${options.category}`,
          scheduledTime: new Date(),
          videoId: '',
          platform: 'instagram',
        };
      }

      // Calculate scheduled time
      const [hours, minutes] = options.time.split(':').map(Number);
      const scheduledTime = new Date(options.date);
      if (hours !== undefined && minutes !== undefined) {
        scheduledTime.setHours(hours, minutes, 0, 0);
      }

      // Generate caption
      const caption = await this.captionService.generateCaption({
        videoId: video.id,
        tone: 'professional',
        includeHashtags: true,
        maxLength: 2200,
      });

      // Create post record
      const post = await this.postModel.create({
        userId,
        videoId: video.id,
        platform: 'instagram',
        content: typeof caption === 'string' ? caption : caption.caption || '',
        hashtags: video.preferredHashtags || [],
        scheduledTime,
        autoGenerated: true,
        contentType: 'video',
        musicUsed: video.preferredMusic,
        thumbnailUsed: video.thumbnailPath,
      });

      logger.info(`Scheduled post ${post.id} for ${scheduledTime}`);

      return {
        success: true,
        postId: post.id,
        scheduledTime,
        videoId: video.id,
        platform: 'instagram',
      };
    } catch (error) {
      logger.error('Failed to schedule single post:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error',
        scheduledTime: new Date(),
        videoId: '',
        platform: 'instagram',
      };
    }
  }

  /**
   * Execute scheduled posts
   */
  async executeScheduledPosts(): Promise<PostingResult[]> {
    try {
      logger.info('Executing scheduled posts...');

      const now = new Date();
      const scheduledPosts = await this.postModel.find({
        status: 'scheduled',
        scheduledTime: { $lte: now },
      });

      const results: PostingResult[] = [];

      for (const post of scheduledPosts) {
        try {
          const result = await this.executePost(post.id);
          results.push(result);
        } catch (error) {
          logger.error(`Failed to execute post ${post.id}:`, error);
          results.push({
            success: false,
            error: error instanceof Error ? error.message : 'Unknown error',
            scheduledTime: post.scheduledTime,
            videoId: post.videoId,
            platform: post.platform,
          });
        }
      }

      logger.info(`Executed ${results.length} scheduled posts`);
      return results;
    } catch (error) {
      logger.error('Failed to execute scheduled posts:', error);
      throw error;
    }
  }

  /**
   * Execute a single post
   */
  private async executePost(postId: string): Promise<PostingResult> {
    try {
      const post = await this.postModel.findById(postId);
      if (!post) {
        throw new Error('Post not found');
      }

      const user = await this.userModel.findById(post.userId);
      if (!user) {
        throw new Error('User not found');
      }

      const video = await this.videoModel.findById(post.videoId);
      if (!video) {
        throw new Error('Video not found');
      }

      // Execute actual post
      const result = await this.instagramService.postVideo({
        videoPath: video.filePath,
        caption: post.content || '',
        hashtags: post.hashtags || [],
        accessToken: user.instagramAccessToken || '',
        userId: user.instagramUserId || '',
      });

      if (result.success) {
        // Mark as posted with engagement metrics
        await this.postModel.findByIdAndUpdate(postId, {
          status: 'posted',
          postedTime: new Date(),
        });

        await this.videoModel.findByIdAndUpdate(video._id, {
          postCount: (video.postCount || 0) + 1,
          lastPostedAt: new Date(),
        });

        // Update analytics
        if (result.engagementMetrics) {
          await this.analyticsService.recordPostEngagement(postId, result.engagementMetrics);
        }

        logger.info(`Successfully posted to Instagram: ${postId}`);
      } else {
        // Mark as failed
        await this.postModel.findByIdAndUpdate(postId, {
          status: 'failed',
          errorMessage: result.error || 'Unknown error',
        });
        logger.error(`Failed to post to Instagram: ${result.error}`);
      }

      return {
        success: result.success,
        postId,
        error: result.error,
        engagementMetrics: result.engagementMetrics,
        scheduledTime: post.scheduledTime,
        videoId: post.videoId,
        platform: post.platform,
      };
    } catch (error) {
      logger.error(`Failed to execute post ${postId}:`, error);
      throw error;
    }
  }

  /**
   * Get optimal posting times based on engagement data
   */
  async getOptimalPostingTimes(userId: string): Promise<string[]> {
    try {
      const engagementData = await this.analyticsService.getBestPostingTimes(userId, 90);

      if (engagementData && engagementData.bestTimes) {
        return engagementData.bestTimes.slice(0, 3); // Top 3 times
      }

      // Default times if no engagement data
      return ['09:00', '13:00', '18:00'];
    } catch (error) {
      logger.error('Failed to get optimal posting times:', error);
      return ['09:00', '13:00', '18:00'];
    }
  }

  /**
   * Smart video selection based on engagement and timing
   */
  async selectNextVideo(
    userId: string,
    _category: string,
    options: SmartPostingOptions = {}
  ): Promise<any> {
    try {
      const nextVideo = await this.videoModel
        .findOne({
          userId,
          isActive: true,
          $or: [{ nextPostDate: { $lte: new Date() } }, { nextPostDate: null }],
        })
        .sort({ lastPostedAt: 1 });

      if (!nextVideo) {
        return null;
      }

      if (options.avoidDuplicateContent && nextVideo) {
        // Check if similar content was posted recently
        const recentPosts = await this.postModel.find({
          userId,
          status: 'posted',
          postedTime: { $gte: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) },
        });

        const hasSimilarContent = recentPosts.some(
          (post: any) =>
            nextVideo &&
            post.videoId === nextVideo.id &&
            post.postedTime &&
            new Date(post.postedTime).getTime() > Date.now() - 7 * 24 * 60 * 60 * 1000 // 7 days
        );

        if (hasSimilarContent && nextVideo) {
          // Get alternative video
          const alternativeVideo = await this.videoModel
            .findOne({
              userId,
              isActive: true,
              $or: [{ nextPostDate: { $lte: new Date() } }, { nextPostDate: null }],
            })
            .sort({ lastPostedAt: 1 });
          return alternativeVideo || null;
        }
      }

      return nextVideo;
    } catch (error) {
      logger.error('Failed to select next video:', error);
      throw error;
    }
  }

  /**
   * Get posting statistics
   */
  async getPostingStats(userId: string, _days: number = 30): Promise<any> {
    try {
      const totalPosts = await this.postModel.countDocuments({ userId });
      const totalVideos = await this.videoModel.countDocuments({ userId });

      return {
        totalPosts,
        totalVideos,
        averageEngagement: 0, // Would calculate from actual engagement data
        successRate: 0.95, // Would calculate from successful vs failed posts
      };
    } catch (error) {
      logger.error('Failed to get posting stats:', error);
      throw error;
    }
  }

  /**
   * Get next scheduled post
   */
  private async getNextScheduledPost(userId: string): Promise<any> {
    try {
      const nextPost = await this.postModel
        .findOne({
          userId,
          status: 'scheduled',
          scheduledTime: { $gt: new Date() },
        })
        .sort({ scheduledTime: 1 });

      return nextPost;
    } catch (error) {
      logger.error('Failed to get next scheduled post:', error);
      return null;
    }
  }

  /**
   * Pause auto-posting for a user
   */
  async pauseAutoPosting(userId: string): Promise<void> {
    try {
      await this.userModel.findByIdAndUpdate(userId, {
        autoPostingEnabled: false,
      });
      logger.info(`Auto-posting paused for user ${userId}`);
    } catch (error) {
      logger.error('Failed to pause auto-posting:', error);
      throw error;
    }
  }

  /**
   * Resume auto-posting for a user
   */
  async resumeAutoPosting(userId: string): Promise<void> {
    try {
      await this.userModel.findByIdAndUpdate(userId, {
        autoPostingEnabled: true,
      });
      logger.info(`Auto-posting resumed for user ${userId}`);
    } catch (error) {
      logger.error('Failed to resume auto-posting:', error);
      throw error;
    }
  }

  /**
   * Manually trigger a post for a user
   */
  async manualPost(userId: string): Promise<PostingResult> {
    try {
      logger.info(`Manual post triggered for user ${userId}`);

      // Get the next scheduled post for this user or create one
      const nextPost = await this.getNextScheduledPost(userId);

      if (nextPost) {
        // Execute the scheduled post immediately
        return await this.executePost(nextPost.id);
      } else {
        // No scheduled posts, let's schedule one and execute it
        const results = await this.schedulePosts(userId, 1);
        if (results.length > 0 && results[0]?.success) {
          // Get the newly created post and execute it
          const newPost = await this.getNextScheduledPost(userId);
          if (newPost) {
            return await this.executePost(newPost.id);
          }
        }

        return {
          success: false,
          error: 'No videos available for posting',
          postId: '',
          scheduledTime: new Date(),
          videoId: '',
          platform: 'instagram',
        };
      }
    } catch (error) {
      logger.error('Error in manual post:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error',
        postId: '',
        scheduledTime: new Date(),
        videoId: '',
        platform: 'instagram',
      };
    }
  }
}

// Export singleton instance for backwards compatibility
export const autoPostingService = new AutoPostingService();

export default AutoPostingService;
