import { Router, Request, Response } from 'express';
import jwt from 'jsonwebtoken';
import { UserModel } from '../models/User';
import { PostModel } from '../models/Post';
import { pool } from '../config/database';
import { logger } from '../utils/logger';

const router = Router();
const userModel = new UserModel(pool);
const postModel = new PostModel(pool);

// JWT Secret
const JWT_SECRET = process.env.JWT_SECRET || 'your-secret-key';

// Authentication middleware
const authenticateToken = (req: Request, res: Response, next: Function) => {
  const token = req.headers.authorization?.replace('Bearer ', '');
  
  if (!token) {
    return res.status(401).json({ error: 'No token provided' });
  }

  try {
    const decoded = jwt.verify(token, JWT_SECRET) as { userId: string };
    (req as any).userId = decoded.userId;
    next();
  } catch (error) {
    return res.status(401).json({ error: 'Invalid token' });
  }
};

// @route   POST /api/instagram/post
// @desc    Post to Instagram
// @access  Private
router.post('/post', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const {
      videoId,
      caption,
      hashtags = [],
      location,
      musicUsed,
      thumbnailUsed,
    } = req.body;

    // Get user's Instagram credentials
    const user = await userModel.findById(userId);
    if (!user || !user.instagramAccessToken) {
      return res.status(400).json({ error: 'Instagram not connected' });
    }

    // Get video details
    const video = await postModel.getVideoById(videoId);
    if (!video || video.userId !== userId) {
      return res.status(404).json({ error: 'Video not found' });
    }

    // Create post record
    const post = await postModel.create({
      userId,
      videoId,
      platform: 'instagram',
      content: caption,
      hashtags,
      scheduledTime: new Date(),
      autoGenerated: false,
      contentType: 'video',
      musicUsed,
      thumbnailUsed,
    });

    // TODO: Implement actual Instagram API posting
    // This would integrate with Instagram's Graph API
    const instagramResponse = {
      id: `ig_${Date.now()}`,
      permalink: `https://www.instagram.com/p/${Date.now()}/`,
      mediaType: 'VIDEO',
    };

    // Mark post as posted
    const updatedPost = await postModel.markAsPosted(post.id, {
      likes: 0,
      comments: 0,
      shares: 0,
      views: 0,
      reach: 0,
      impressions: 0,
      engagementRate: 0,
      instagramPostId: instagramResponse.id,
      instagramPermalink: instagramResponse.permalink,
    });

    logger.info(`Posted to Instagram: ${post.id} for user ${userId}`);

    res.json({
      message: 'Posted to Instagram successfully',
      post: {
        id: updatedPost.id,
        instagramPostId: instagramResponse.id,
        permalink: instagramResponse.permalink,
        status: updatedPost.status,
      }
    });
  } catch (error) {
    logger.error('Instagram post error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// @route   GET /api/instagram/connect
// @desc    Get Instagram authorization URL
// @access  Private
router.get('/connect', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const { redirectUri } = req.query;

    if (!redirectUri) {
      return res.status(400).json({ error: 'Redirect URI is required' });
    }

    const instagramAppId = process.env.INSTAGRAM_APP_ID;
    const instagramRedirectUri = process.env.INSTAGRAM_REDIRECT_URI;

    if (!instagramAppId) {
      return res.status(500).json({ error: 'Instagram app not configured' });
    }

    const authUrl = `https://api.instagram.com/oauth/authorize?client_id=${instagramAppId}&redirect_uri=${instagramRedirectUri}&scope=user_profile,user_media&response_type=code&state=${userId}`;

    res.json({
      authUrl,
      message: 'Use this URL to authorize Instagram access',
    });
  } catch (error) {
    logger.error('Instagram connect error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// @route   POST /api/instagram/callback
// @desc    Handle Instagram authorization callback
// @access  Public
router.post('/callback', async (req: Request, res: Response) => {
  try {
    const { code, state } = req.body;

    if (!code || !state) {
      return res.status(400).json({ error: 'Authorization code and state are required' });
    }

    const userId = state;
    const instagramAppId = process.env.INSTAGRAM_APP_ID;
    const instagramAppSecret = process.env.INSTAGRAM_APP_SECRET;
    const instagramRedirectUri = process.env.INSTAGRAM_REDIRECT_URI;

    if (!instagramAppId || !instagramAppSecret) {
      return res.status(500).json({ error: 'Instagram app not configured' });
    }

    // Exchange code for access token
    const tokenResponse = await fetch('https://api.instagram.com/oauth/access_token', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: new URLSearchParams({
        client_id: instagramAppId,
        client_secret: instagramAppSecret,
        grant_type: 'authorization_code',
        redirect_uri: instagramRedirectUri,
        code,
      }),
    });

    const tokenData = await tokenResponse.json();

    if (!tokenData.access_token) {
      return res.status(400).json({ error: 'Failed to get access token' });
    }

    // Get user info
    const userResponse = await fetch(`https://graph.instagram.com/me?fields=id,username&access_token=${tokenData.access_token}`);
    const userData = await userResponse.json();

    // Update user's Instagram credentials
    await userModel.updateInstagramCredentials(userId, {
      instagramUsername: userData.username,
      instagramAccessToken: tokenData.access_token,
      instagramUserId: userData.id,
    });

    logger.info(`Instagram connected for user: ${userId}`);

    res.json({
      message: 'Instagram connected successfully',
      user: {
        instagramUsername: userData.username,
        instagramUserId: userData.id,
      }
    });
  } catch (error) {
    logger.error('Instagram callback error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// @route   GET /api/instagram/account
// @desc    Get Instagram account info
// @access  Private
router.get('/account', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;

    const user = await userModel.findById(userId);
    if (!user || !user.instagramAccessToken) {
      return res.status(400).json({ error: 'Instagram not connected' });
    }

    // Get account info from Instagram API
    const accountResponse = await fetch(`https://graph.instagram.com/me?fields=id,username,account_type,media_count&access_token=${user.instagramAccessToken}`);
    const accountData = await accountResponse.json();

    res.json({
      account: {
        id: accountData.id,
        username: accountData.username,
        accountType: accountData.account_type,
        mediaCount: accountData.media_count,
        connected: true,
      }
    });
  } catch (error) {
    logger.error('Get Instagram account error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// @route   GET /api/instagram/media
// @desc    Get Instagram media
// @access  Private
router.get('/media', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const { limit = 20, after } = req.query;

    const user = await userModel.findById(userId);
    if (!user || !user.instagramAccessToken) {
      return res.status(400).json({ error: 'Instagram not connected' });
    }

    // Get media from Instagram API
    let url = `https://graph.instagram.com/me/media?fields=id,caption,media_type,media_url,thumbnail_url,permalink,timestamp,like_count,comments_count&access_token=${user.instagramAccessToken}&limit=${limit}`;
    
    if (after) {
      url += `&after=${after}`;
    }

    const mediaResponse = await fetch(url);
    const mediaData = await mediaResponse.json();

    res.json({
      media: mediaData.data,
      paging: mediaData.paging,
    });
  } catch (error) {
    logger.error('Get Instagram media error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// @route   POST /api/instagram/refresh-token
// @desc    Refresh Instagram access token
// @access  Private
router.post('/refresh-token', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;

    const user = await userModel.findById(userId);
    if (!user || !user.instagramAccessToken) {
      return res.status(400).json({ error: 'Instagram not connected' });
    }

    const instagramAppSecret = process.env.INSTAGRAM_APP_SECRET;

    if (!instagramAppSecret) {
      return res.status(500).json({ error: 'Instagram app not configured' });
    }

    // Exchange current token for long-lived token
    const tokenResponse = await fetch('https://graph.instagram.com/access_token', {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        grant_type: 'ig_exchange_token',
        client_secret: instagramAppSecret,
        access_token: user.instagramAccessToken,
      }),
    });

    const tokenData = await tokenResponse.json();

    if (!tokenData.access_token) {
      return res.status(400).json({ error: 'Failed to refresh token' });
    }

    // Update user's token
    await userModel.updateInstagramCredentials(userId, {
      instagramAccessToken: tokenData.access_token,
    });

    logger.info(`Instagram token refreshed for user: ${userId}`);

    res.json({
      message: 'Instagram token refreshed successfully',
      expiresIn: tokenData.expires_in,
    });
  } catch (error) {
    logger.error('Refresh Instagram token error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// @route   DELETE /api/instagram/disconnect
// @desc    Disconnect Instagram account
// @access  Private
router.delete('/disconnect', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;

    // Clear Instagram credentials
    await userModel.updateInstagramCredentials(userId, {
      instagramUsername: null,
      instagramAccessToken: null,
      instagramRefreshToken: null,
      instagramUserId: null,
    });

    logger.info(`Instagram disconnected for user: ${userId}`);

    res.json({ message: 'Instagram disconnected successfully' });
  } catch (error) {
    logger.error('Disconnect Instagram error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// @route   GET /api/instagram/insights
// @desc    Get Instagram insights
// @access  Private
router.get('/insights', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const { days = 30 } = req.query;

    const user = await userModel.findById(userId);
    if (!user || !user.instagramAccessToken) {
      return res.status(400).json({ error: 'Instagram not connected' });
    }

    // Get insights from Instagram API
    const insightsResponse = await fetch(`https://graph.instagram.com/me/insights?metric=impressions,reach,profile_views&period=day&access_token=${user.instagramAccessToken}`);
    const insightsData = await insightsResponse.json();

    res.json({
      insights: insightsData.data,
      period: 'day',
      days: parseInt(days as string),
    });
  } catch (error) {
    logger.error('Get Instagram insights error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

export default router; 