import { Router, Request, Response } from 'express';
// import jwt from 'jsonwebtoken';
import { User } from '../models/User';
import { Post } from '../models/Post';
import { Video } from '../models/Video';
import { connectToDatabase } from '../config/database';
import { logger } from '../utils/logger';
import { authenticateToken } from '../middleware/auth';

const router = Router();

// JWT Secret
// const JWT_SECRET = process.env.JWT_SECRET || 'your-secret-key';

// @route   POST /api/instagram/post
// @desc    Post to Instagram
// @access  Private
router.post('/post', authenticateToken, async (req: Request, res: Response) => {
  try {
    await connectToDatabase();
    const userId = req.user!.id;
    const {
      videoId,
      caption,
      hashtags = [],
      location: _location,
      musicUsed,
      thumbnailUsed,
    } = req.body;

    // Get user's Instagram credentials
    const user = await User.findById(userId);
    if (!user || !user.instagramAccessToken) {
      return res.status(400).json({ error: 'Instagram not connected' });
    }

    // Get video details
    const video = await Video.findOne({ _id: videoId, userId });
    if (!video) {
      return res.status(404).json({ error: 'Video not found or access denied' });
    }

    // Create post record
    const newPost = new Post({
      userId,
      videoId,
      platform: 'instagram',
      content: caption,
      hashtags: Array.isArray(hashtags) ? hashtags : [],
      scheduledTime: new Date(),
      autoGenerated: false,
      contentType: 'video',
      musicUsed,
      thumbnailUsed
    });

    const savedPost = await newPost.save();

    // Update video post count
    await Video.findByIdAndUpdate(videoId, {
      $inc: { postCount: 1 },
      $set: { lastPostedAt: new Date() }
    });

    return res.json({
      success: true,
      message: 'Post created successfully',
      postId: savedPost._id,
      instagramPostId: `mock_${Date.now()}` // In real implementation, this would come from Instagram API
        });
  } catch (error) {
    logger.error('Instagram post error:', error);
    return res.status(500).json({ error: 'Failed to create Instagram post' });
  }
});

// @route   GET /api/instagram/connect
// @desc    Get Instagram authorization URL
// @access  Private
router.get('/connect', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const { redirectUri } = req.query;

    if (!redirectUri) {
      return res.status(400).json({ error: 'Redirect URI is required' });
    }

    const instagramAppId = process.env.INSTAGRAM_APP_ID;
    const instagramRedirectUri = process.env.INSTAGRAM_REDIRECT_URI;

    if (!instagramAppId) {
      return res.status(500).json({ error: 'Instagram app not configured' });
    }

    const authUrl = `https://api.instagram.com/oauth/authorize?client_id=${instagramAppId}&redirect_uri=${instagramRedirectUri}&scope=user_profile,user_media&response_type=code&state=${userId}`;

    return res.json({
      authUrl,
      message: 'Use this URL to authorize Instagram access',
    });
  } catch (error) {
    logger.error('Instagram connect error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

// @route   POST /api/instagram/callback
// @desc    Handle Instagram authorization callback
// @access  Public
router.post('/callback', async (req: Request, res: Response) => {
  try {
    const { code, state } = req.body;

    if (!code || !state) {
      return res.status(400).json({ error: 'Authorization code and state are required' });
    }

    const userId = state;
    const instagramAppId = process.env.INSTAGRAM_APP_ID;
    const instagramAppSecret = process.env.INSTAGRAM_APP_SECRET;
    const instagramRedirectUri = process.env.INSTAGRAM_REDIRECT_URI;

    if (!instagramAppId || !instagramAppSecret) {
      return res.status(500).json({ error: 'Instagram app not configured' });
    }

    // Exchange code for access token
    const tokenResponse = await fetch('https://api.instagram.com/oauth/access_token', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: new URLSearchParams({
        client_id: instagramAppId,
        client_secret: instagramAppSecret,
        grant_type: 'authorization_code',
        redirect_uri: instagramRedirectUri || '',
        code,
      }),
    });

    const tokenData = await tokenResponse.json() as { access_token?: string };

    if (!tokenData.access_token) {
      return res.status(400).json({ error: 'Failed to get access token' });
    }

    // Get user info
    const userResponse = await fetch(`https://graph.instagram.com/me?fields=id,username&access_token=${tokenData.access_token}`);
    const userData = await userResponse.json() as { id: string; username: string };

    // Update user's Instagram credentials
    await User.findByIdAndUpdate(userId, {
      instagramAccessToken: tokenData.access_token,
      instagramUserId: userData.id,
      username: userData.username,
    });

    logger.info(`Instagram connected for user: ${userId}`);

    return res.json({
      message: 'Instagram connected successfully',
      user: {
        instagramUsername: userData.username,
        instagramUserId: userData.id,
      }
    });
  } catch (error) {
    logger.error('Instagram callback error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

// @route   GET /api/instagram/account
// @desc    Get Instagram account info
// @access  Private
router.get('/account', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;

    const user = await User.findById(userId);
    if (!user || !user.instagramAccessToken) {
      return res.status(400).json({ error: 'Instagram not connected' });
    }

    // Get account info from Instagram API
    const accountResponse = await fetch(`https://graph.instagram.com/me?fields=id,username,account_type,media_count&access_token=${user.instagramAccessToken}`);
    const accountData = await accountResponse.json() as {
      id: string;
      username: string;
      account_type: string;
      media_count: number;
    };

    return res.json({
      account: {
        id: accountData.id,
        username: accountData.username,
        accountType: accountData.account_type,
        mediaCount: accountData.media_count,
        connected: true,
      }
    });
  } catch (error) {
    logger.error('Get Instagram account error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

// @route   GET /api/instagram/media
// @desc    Get Instagram media
// @access  Private
router.get('/media', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const { limit = 20, after } = req.query;

    const user = await User.findById(userId);
    if (!user || !user.instagramAccessToken) {
      return res.status(400).json({ error: 'Instagram not connected' });
    }

    // Get media from Instagram API
    let url = `https://graph.instagram.com/me/media?fields=id,caption,media_type,media_url,thumbnail_url,permalink,timestamp,like_count,comments_count&access_token=${user.instagramAccessToken}&limit=${limit}`;
    
    if (after) {
      url += `&after=${after}`;
    }

    const mediaResponse = await fetch(url);
    const mediaData = await mediaResponse.json() as {
      data: any[];
      paging?: any;
    };

    return res.json({
      media: mediaData.data,
      paging: mediaData.paging,
    });
  } catch (error) {
    logger.error('Get Instagram media error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

// @route   POST /api/instagram/refresh-token
// @desc    Refresh Instagram access token
// @access  Private
router.post('/refresh-token', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;

    const user = await User.findById(userId);
    if (!user || !user.instagramAccessToken) {
      return res.status(400).json({ error: 'Instagram not connected' });
    }

    const instagramAppSecret = process.env.INSTAGRAM_APP_SECRET;

    if (!instagramAppSecret) {
      return res.status(500).json({ error: 'Instagram app not configured' });
    }

    // Exchange current token for long-lived token
    const tokenUrl = `https://graph.instagram.com/access_token?grant_type=ig_exchange_token&client_secret=${instagramAppSecret}&access_token=${user.instagramAccessToken}`;
    
    const tokenResponse = await fetch(tokenUrl, {
      method: 'GET',
    });

    const tokenData = await tokenResponse.json() as {
      access_token?: string;
      expires_in?: number;
    };

    if (!tokenData.access_token) {
      return res.status(400).json({ error: 'Failed to refresh token' });
    }

    // Update user's token
    await User.findByIdAndUpdate(userId, {
      instagramAccessToken: tokenData.access_token,
    });

    logger.info(`Instagram token refreshed for user: ${userId}`);

    return res.json({
      message: 'Instagram token refreshed successfully',
      expiresIn: tokenData.expires_in,
    });
  } catch (error) {
    logger.error('Refresh Instagram token error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

// @route   DELETE /api/instagram/disconnect
// @desc    Disconnect Instagram account
// @access  Private
router.delete('/disconnect', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;

    // Clear Instagram credentials
    await User.findByIdAndUpdate(userId, {
      instagramAccessToken: null,
      instagramUserId: null,
      username: null,
    });

    logger.info(`Instagram disconnected for user: ${userId}`);

    return res.json({ message: 'Instagram disconnected successfully' });
  } catch (error) {
    logger.error('Disconnect Instagram error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

// @route   GET /api/instagram/insights
// @desc    Get Instagram insights
// @access  Private
router.get('/insights', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const { days = 30 } = req.query;

    const user = await User.findById(userId);
    if (!user || !user.instagramAccessToken) {
      return res.status(400).json({ error: 'Instagram not connected' });
    }

    // Get insights from Instagram API
    const insightsResponse = await fetch(`https://graph.instagram.com/me/insights?metric=impressions,reach,profile_views&period=day&access_token=${user.instagramAccessToken}`);
    const insightsData = await insightsResponse.json() as {
      data: any[];
    };

    return res.json({
      insights: insightsData.data,
      period: 'day',
      days: parseInt(days as string),
    });
  } catch (error) {
    logger.error('Get Instagram insights error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

export default router; 