import { Router, Request, Response } from 'express';
// import jwt from 'jsonwebtoken';
import { Post } from '../models/Post';
import { Video } from '../models/Video';
import { connectToDatabase } from '../config/database';
import { logger } from '../utils/logger';
import { authenticateToken } from '../middleware/auth';

const router = Router();

// JWT Secret
// const JWT_SECRET = process.env.JWT_SECRET || 'your-secret-key';

// @route   POST /api/posts/schedule
// @desc    Schedule a new post
// @access  Private
router.post('/schedule', authenticateToken, async (req: Request, res: Response) => {
  try {
    await connectToDatabase();
    
    const {
      videoId,
      platform,
      content,
      hashtags = [],
      scheduledTime,
      autoGenerated = false,
      contentType = 'video',
      musicUsed,
      thumbnailUsed
    } = req.body;

    const userId = req.user!.id;

    // Validate required fields
    if (!videoId || !platform || !content || !scheduledTime) {
      return res.status(400).json({
        error: 'Missing required fields: videoId, platform, content, scheduledTime'
      });
    }

    // Verify video exists and belongs to user
    const video = await Video.findOne({ _id: videoId, userId });
    if (!video) {
      return res.status(404).json({ error: 'Video not found or access denied' });
    }

    // Create new post
    const newPost = new Post({
      userId,
      videoId,
      platform,
      content,
      hashtags: Array.isArray(hashtags) ? hashtags : [],
      scheduledTime: new Date(scheduledTime),
      autoGenerated,
      contentType,
      musicUsed,
      thumbnailUsed
    });

    const savedPost = await newPost.save();

    return res.status(201).json({
      message: 'Post scheduled successfully',
      post: savedPost
        });
  } catch (error) {
    logger.error('Error scheduling post:', error);
    return res.status(500).json({ error: 'Failed to schedule post' });
  }
});

// @route   GET /api/posts
// @desc    Get user's posts
// @access  Private
router.get('/', authenticateToken, async (req: Request, res: Response) => {
  try {
    await connectToDatabase();
    const userId = req.user!.id;
    const { status, platform, limit, offset, startDate: _startDate, endDate: _endDate } = req.query;

    const posts = await Post.find({ userId, ...(status ? { status } : {}), ...(platform ? { platform } : {}) })
      .sort({ scheduledTime: 1 })
      .skip(offset ? parseInt(offset as string) : 0)
      .limit(limit ? parseInt(limit as string) : 10);

    return res.json({ posts });
  } catch (error) {
    logger.error('Get posts error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

// @route   GET /api/posts/:id
// @desc    Get post by ID
// @access  Private
router.get('/:id', authenticateToken, async (req: Request, res: Response) => {
  try {
    await connectToDatabase();
    const userId = req.user!.id;
    const postId = req.params.id;
    
    if (!postId) {
      return res.status(400).json({ error: 'Post ID is required' });
    }
    
    const post = await Post.findById(postId);
    if (!post) {
      return res.status(404).json({ error: 'Post not found' });
    }
    
    // Check if user owns the post
    if (post.userId.toString() !== userId) {
      return res.status(403).json({ error: 'Access denied' });
    }
    
    return res.json(post);
  } catch (error) {
    logger.error('Get post error:', error);
    return res.status(500).json({ error: 'Failed to fetch post' });
  }
});

// @route   PUT /api/posts/:id
// @desc    Update post
// @access  Private
router.put('/:id', authenticateToken, async (req: Request, res: Response) => {
  try {
    await connectToDatabase();
    const userId = req.user!.id;
    const postId = req.params.id;

    if (!postId) {
      return res.status(400).json({ error: 'Post ID is required' });
    }

    const post = await Post.findById(postId);

    if (!post || post.userId.toString() !== userId) {
      return res.status(404).json({ error: 'Post not found' });
    }

    const {
      content,
      hashtags,
      scheduledTime,
      musicUsed,
      thumbnailUsed,
    } = req.body;

    const updatedPost = await Post.findByIdAndUpdate(postId, {
      content,
      hashtags: Array.isArray(hashtags) ? hashtags : [],
      scheduledTime: scheduledTime ? new Date(scheduledTime) : undefined,
      musicUsed,
      thumbnailUsed,
    }, { new: true });

    if (!updatedPost) {
      return res.status(404).json({ error: 'Post not found' });
    }

    logger.info(`Post updated: ${updatedPost._id} by user ${userId}`);

    return res.json({
      message: 'Post updated successfully',
      post: updatedPost,
    });
  } catch (error) {
    logger.error('Update post error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

// @route   DELETE /api/posts/:id
// @desc    Cancel/delete post
// @access  Private
router.delete('/:id', authenticateToken, async (req: Request, res: Response) => {
  try {
    await connectToDatabase();
    const userId = req.user!.id;
    const postId = req.params.id;

    if (!postId) {
      return res.status(400).json({ error: 'Post ID is required' });
    }

    const post = await Post.findById(postId);

    if (!post || post.userId.toString() !== userId) {
      return res.status(404).json({ error: 'Post not found' });
    }

    // Only allow cancellation of scheduled posts
    if (post.status !== 'scheduled') {
      return res.status(400).json({ error: 'Only scheduled posts can be cancelled' });
    }

    const updatedPost = await Post.findByIdAndUpdate(postId, {
      status: 'cancelled',
    }, { new: true });

    if (!updatedPost) {
      return res.status(404).json({ error: 'Post not found' });
    }

    logger.info(`Post cancelled: ${updatedPost._id} by user ${userId}`);

    return res.json({ message: 'Post cancelled successfully' });
  } catch (error) {
    logger.error('Cancel post error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

// @route   GET /api/posts/scheduled
// @desc    Get scheduled posts for a date range
// @access  Private
router.get('/scheduled', authenticateToken, async (req: Request, res: Response) => {
  try {
    await connectToDatabase();
    const userId = req.user!.id;
    const { startDate, endDate } = req.query;

    if (!startDate || !endDate) {
      return res.status(400).json({ error: 'Start date and end date are required' });
    }

    const posts = await Post.find({
      userId,
      scheduledTime: {
        $gte: new Date(startDate as string),
        $lte: new Date(endDate as string),
      },
      status: 'scheduled',
    }).sort({ scheduledTime: 1 });

    return res.json({ posts });
  } catch (error) {
    logger.error('Get scheduled posts error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

// @route   POST /api/posts/:id/mark-posted
// @desc    Mark post as posted (for successful posts)
// @access  Private
router.post('/:id/mark-posted', authenticateToken, async (req: Request, res: Response) => {
  try {
    await connectToDatabase();
    const userId = req.user!.id;
    const postId = req.params.id;
    const { engagementMetrics } = req.body;

    if (!postId) {
      return res.status(400).json({ error: 'Post ID is required' });
    }

    const post = await Post.findById(postId);

    if (!post || post.userId.toString() !== userId) {
      return res.status(404).json({ error: 'Post not found' });
    }

    const updatedPost = await Post.findByIdAndUpdate(postId, {
      status: 'posted',
      postedTime: new Date(),
      engagementMetrics,
    }, { new: true });

    if (!updatedPost) {
      return res.status(404).json({ error: 'Post not found' });
    }

         // Mark video as posted
     await Video.findByIdAndUpdate(post.videoId, { 
       $inc: { postCount: 1 },
       $set: { lastPostedAt: new Date() }
     });

    logger.info(`Post marked as posted: ${updatedPost._id} by user ${userId}`);

    return res.json({
      message: 'Post marked as posted successfully',
      post: {
        id: updatedPost._id,
        status: updatedPost.status,
        postedTime: updatedPost.postedTime,
        engagementMetrics: updatedPost.engagementMetrics,
      }
    });
  } catch (error) {
    logger.error('Mark post posted error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

// @route   POST /api/posts/:id/mark-failed
// @desc    Mark post as failed
// @access  Private
router.post('/:id/mark-failed', authenticateToken, async (req: Request, res: Response) => {
  try {
    await connectToDatabase();
    const userId = req.user!.id;
    const postId = req.params.id;
    const { errorMessage } = req.body;

    if (!postId) {
      return res.status(400).json({ error: 'Post ID is required' });
    }

    const post = await Post.findById(postId);

    if (!post || post.userId.toString() !== userId) {
      return res.status(404).json({ error: 'Post not found' });
    }

    const updatedPost = await Post.findByIdAndUpdate(postId, {
      status: 'failed',
      errorMessage,
      retryCount: post.retryCount + 1,
    }, { new: true });

    if (!updatedPost) {
      return res.status(404).json({ error: 'Post not found' });
    }

    logger.info(`Post marked as failed: ${updatedPost._id} by user ${userId}`);

    return res.json({
      message: 'Post marked as failed',
      post: {
        id: updatedPost._id,
        status: updatedPost.status,
        errorMessage: updatedPost.errorMessage,
        retryCount: updatedPost.retryCount,
      }
    });
  } catch (error) {
    logger.error('Mark post failed error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

// @route   GET /api/posts/stats
// @desc    Get posting statistics
// @access  Private
router.get('/stats', authenticateToken, async (req: Request, res: Response) => {
  try {
    await connectToDatabase();
    const userId = req.user!.id;
    const { days = 30 } = req.query;

         // Get posting stats using aggregation
     const daysAgo = new Date();
     daysAgo.setDate(daysAgo.getDate() - parseInt(days as string));
     
     const stats = await Post.aggregate([
       { $match: { userId, createdAt: { $gte: daysAgo } } },
       {
         $group: {
           _id: null,
           totalPosts: { $sum: 1 },
           successfulPosts: { $sum: { $cond: [{ $eq: ['$status', 'posted'] }, 1, 0] } },
           failedPosts: { $sum: { $cond: [{ $eq: ['$status', 'failed'] }, 1, 0] } },
           scheduledPosts: { $sum: { $cond: [{ $eq: ['$status', 'scheduled'] }, 1, 0] } },
           instagramPosts: { $sum: { $cond: [{ $eq: ['$platform', 'instagram'] }, 1, 0] } },
           tiktokPosts: { $sum: { $cond: [{ $eq: ['$platform', 'tiktok'] }, 1, 0] } },
           facebookPosts: { $sum: { $cond: [{ $eq: ['$platform', 'facebook'] }, 1, 0] } }
         }
       }
     ]);
     
     const result = stats[0] || {
       totalPosts: 0,
       successfulPosts: 0,
       failedPosts: 0,
       scheduledPosts: 0,
       instagramPosts: 0,
       tiktokPosts: 0,
       facebookPosts: 0
     };

         return res.json({ 
       stats: {
         ...result,
         byPlatform: {
           instagram: result.instagramPosts,
           tiktok: result.tiktokPosts,
           facebook: result.facebookPosts
         }
       }
     });
  } catch (error) {
    logger.error('Get post stats error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

// @route   GET /api/posts/failed/retry
// @desc    Get failed posts that can be retried
// @access  Private
router.get('/failed/retry', authenticateToken, async (req: Request, res: Response) => {
  try {
    await connectToDatabase();
    const userId = req.user!.id;
    const { maxRetries = 3 } = req.query;

         // Get failed posts for retry
     const maxRetriesInt = parseInt(maxRetries as string);
     const oneDayAgo = new Date();
     oneDayAgo.setDate(oneDayAgo.getDate() - 1);
     
     const posts = await Post.find({
       userId,
       status: 'failed',
       retryCount: { $lt: maxRetriesInt },
       scheduledTime: { $gte: oneDayAgo }
     }).sort({ scheduledTime: 1 });

    return res.json({ posts });
  } catch (error) {
    logger.error('Get failed posts error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

// @route   POST /api/posts/auto-schedule
// @desc    Auto-schedule posts for the next few days
// @access  Private
router.post('/auto-schedule', authenticateToken, async (req: Request, res: Response) => {
  try {
    await connectToDatabase();
    const userId = req.user!.id;
    const { days = 7, postsPerDay = 3 } = req.body;

    // This would integrate with the smart posting time algorithm
    // For now, we'll create a basic implementation
    const scheduledPosts = [];

    for (let day = 0; day < days; day++) {
      const date = new Date();
      date.setDate(date.getDate() + day);

      for (let post = 0; post < postsPerDay; post++) {
        // Get next video for posting
        const category = post % 2 === 0 ? 'real-estate' : 'cartoon';
                 // Get next video for posting
         const coolOffDate = new Date();
         coolOffDate.setDate(coolOffDate.getDate() - 30); // 30 days cool-off
         
         const video = await Video.findOne({
           userId,
           category,
           isActive: true,
           $or: [
             { lastPostedAt: null },
             { lastPostedAt: { $lt: coolOffDate } }
           ]
         }).sort({ starred: -1, postCount: 1 });

        if (video) {
          // Schedule post at default times (9am, 1pm, 6pm)
          const postingTimes = ['09:00', '13:00', '17:00'];
          const scheduledTime = new Date(date);
          const timeIndex = Math.floor(Math.random() * postingTimes.length);
          const selectedTime = postingTimes[timeIndex];

          if (selectedTime) {
            const timeParts = selectedTime.split(':');
            const hours = timeParts[0];
            const minutes = timeParts[1];
            
            if (hours && minutes) {
              scheduledTime.setHours(parseInt(hours), parseInt(minutes), 0, 0);
            }
          }

          // Properly type the platform and contentType with explicit type assertions
          const platform = 'instagram' as const;
          const contentType = 'video' as const;

          const postData = {
            userId,
            videoId: video.id,
            platform,
            content: video.preferredCaption || `Check out this amazing ${video.category} content!`,
            hashtags: video.preferredHashtags || ['realestate', 'homes', 'property'],
            scheduledTime,
            autoGenerated: true,
            contentType,
            musicUsed: video.preferredMusic,
            thumbnailUsed: video.thumbnailPath,
          };

          const newPost = new Post(postData);
          const savedPost = await newPost.save();
          scheduledPosts.push(savedPost);

                     // Mark video as posted
           await Video.findByIdAndUpdate(video._id, { 
             $inc: { postCount: 1 },
             $set: { lastPostedAt: new Date() }
           });
        }
      }
    }

    logger.info(`Auto-scheduled ${scheduledPosts.length} posts for user ${userId}`);

    return res.json({
      message: `Auto-scheduled ${scheduledPosts.length} posts`,
      posts: scheduledPosts.map(post => ({
        id: post._id,
        videoId: post.videoId,
        scheduledTime: post.scheduledTime,
        status: post.status,
      })),
    });
  } catch (error) {
    logger.error('Auto-schedule posts error:', error);
    return res.status(500).json({ error: 'Server error' });
  }
});

export default router; 