import { Router, Request, Response } from 'express';
import jwt from 'jsonwebtoken';
import { PostModel } from '../models/Post';
import { VideoModel } from '../models/Video';
import { pool } from '../config/database';
import { logger } from '../utils/logger';

const router = Router();
const postModel = new PostModel(pool);
const videoModel = new VideoModel(pool);

// JWT Secret
const JWT_SECRET = process.env.JWT_SECRET || 'your-secret-key';

// Authentication middleware
const authenticateToken = (req: Request, res: Response, next: Function) => {
  const token = req.headers.authorization?.replace('Bearer ', '');
  
  if (!token) {
    return res.status(401).json({ error: 'No token provided' });
  }

  try {
    const decoded = jwt.verify(token, JWT_SECRET) as { userId: string };
    (req as any).userId = decoded.userId;
    next();
  } catch (error) {
    return res.status(401).json({ error: 'Invalid token' });
  }
};

// @route   POST /api/posts/schedule
// @desc    Schedule a new post
// @access  Private
router.post('/schedule', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const {
      videoId,
      platform = 'instagram',
      content,
      hashtags = [],
      scheduledTime,
      autoGenerated = true,
      contentType = 'video',
      musicUsed,
      thumbnailUsed,
    } = req.body;

    // Validate video exists and belongs to user
    const video = await videoModel.findById(videoId);
    if (!video || video.userId !== userId) {
      return res.status(404).json({ error: 'Video not found' });
    }

    // Create post
    const post = await postModel.create({
      userId,
      videoId,
      platform,
      content,
      hashtags,
      scheduledTime: new Date(scheduledTime),
      autoGenerated,
      contentType,
      musicUsed,
      thumbnailUsed,
    });

    logger.info(`Post scheduled: ${post.id} for user ${userId}`);

    res.status(201).json({
      message: 'Post scheduled successfully',
      post: {
        id: post.id,
        videoId: post.videoId,
        platform: post.platform,
        content: post.content,
        hashtags: post.hashtags,
        scheduledTime: post.scheduledTime,
        status: post.status,
      }
    });
  } catch (error) {
    logger.error('Schedule post error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// @route   GET /api/posts
// @desc    Get user's posts
// @access  Private
router.get('/', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const { status, platform, limit, offset, startDate, endDate } = req.query;

    const posts = await postModel.findByUser(userId, {
      status: status as 'scheduled' | 'posted' | 'failed' | 'cancelled',
      platform: platform as 'instagram' | 'tiktok' | 'facebook',
      limit: limit ? parseInt(limit as string) : undefined,
      offset: offset ? parseInt(offset as string) : undefined,
      startDate: startDate ? new Date(startDate as string) : undefined,
      endDate: endDate ? new Date(endDate as string) : undefined,
    });

    res.json({ posts });
  } catch (error) {
    logger.error('Get posts error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// @route   GET /api/posts/:id
// @desc    Get post by ID
// @access  Private
router.get('/:id', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const postId = req.params.id;

    const post = await postModel.findById(postId);

    if (!post || post.userId !== userId) {
      return res.status(404).json({ error: 'Post not found' });
    }

    res.json(post);
  } catch (error) {
    logger.error('Get post error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// @route   PUT /api/posts/:id
// @desc    Update post
// @access  Private
router.put('/:id', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const postId = req.params.id;

    const post = await postModel.findById(postId);

    if (!post || post.userId !== userId) {
      return res.status(404).json({ error: 'Post not found' });
    }

    const {
      content,
      hashtags,
      scheduledTime,
      musicUsed,
      thumbnailUsed,
    } = req.body;

    const updatedPost = await postModel.update(postId, {
      content,
      hashtags,
      scheduledTime: scheduledTime ? new Date(scheduledTime) : undefined,
      musicUsed,
      thumbnailUsed,
    });

    if (!updatedPost) {
      return res.status(404).json({ error: 'Post not found' });
    }

    logger.info(`Post updated: ${updatedPost.id} by user ${userId}`);

    res.json({
      message: 'Post updated successfully',
      post: updatedPost,
    });
  } catch (error) {
    logger.error('Update post error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// @route   DELETE /api/posts/:id
// @desc    Cancel/delete post
// @access  Private
router.delete('/:id', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const postId = req.params.id;

    const post = await postModel.findById(postId);

    if (!post || post.userId !== userId) {
      return res.status(404).json({ error: 'Post not found' });
    }

    // Only allow cancellation of scheduled posts
    if (post.status !== 'scheduled') {
      return res.status(400).json({ error: 'Only scheduled posts can be cancelled' });
    }

    const updatedPost = await postModel.update(postId, {
      status: 'cancelled',
    });

    if (!updatedPost) {
      return res.status(404).json({ error: 'Post not found' });
    }

    logger.info(`Post cancelled: ${updatedPost.id} by user ${userId}`);

    res.json({ message: 'Post cancelled successfully' });
  } catch (error) {
    logger.error('Cancel post error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// @route   GET /api/posts/scheduled
// @desc    Get scheduled posts for a date range
// @access  Private
router.get('/scheduled', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const { startDate, endDate } = req.query;

    if (!startDate || !endDate) {
      return res.status(400).json({ error: 'Start date and end date are required' });
    }

    const posts = await postModel.getScheduledPosts(
      userId,
      new Date(startDate as string),
      new Date(endDate as string)
    );

    res.json({ posts });
  } catch (error) {
    logger.error('Get scheduled posts error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// @route   POST /api/posts/:id/mark-posted
// @desc    Mark post as posted (for successful posts)
// @access  Private
router.post('/:id/mark-posted', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const postId = req.params.id;
    const { engagementMetrics } = req.body;

    const post = await postModel.findById(postId);

    if (!post || post.userId !== userId) {
      return res.status(404).json({ error: 'Post not found' });
    }

    const updatedPost = await postModel.markAsPosted(postId, engagementMetrics);

    if (!updatedPost) {
      return res.status(404).json({ error: 'Post not found' });
    }

    // Mark video as posted
    await videoModel.markAsPosted(post.videoId);

    logger.info(`Post marked as posted: ${updatedPost.id} by user ${userId}`);

    res.json({
      message: 'Post marked as posted successfully',
      post: {
        id: updatedPost.id,
        status: updatedPost.status,
        postedTime: updatedPost.postedTime,
        engagementMetrics: updatedPost.engagementMetrics,
      }
    });
  } catch (error) {
    logger.error('Mark post posted error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// @route   POST /api/posts/:id/mark-failed
// @desc    Mark post as failed
// @access  Private
router.post('/:id/mark-failed', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const postId = req.params.id;
    const { errorMessage } = req.body;

    const post = await postModel.findById(postId);

    if (!post || post.userId !== userId) {
      return res.status(404).json({ error: 'Post not found' });
    }

    const updatedPost = await postModel.markAsFailed(postId, errorMessage);

    if (!updatedPost) {
      return res.status(404).json({ error: 'Post not found' });
    }

    logger.info(`Post marked as failed: ${updatedPost.id} by user ${userId}`);

    res.json({
      message: 'Post marked as failed',
      post: {
        id: updatedPost.id,
        status: updatedPost.status,
        errorMessage: updatedPost.errorMessage,
        retryCount: updatedPost.retryCount,
      }
    });
  } catch (error) {
    logger.error('Mark post failed error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// @route   GET /api/posts/stats
// @desc    Get posting statistics
// @access  Private
router.get('/stats', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const { days = 30 } = req.query;

    const stats = await postModel.getPostingStats(userId, parseInt(days as string));

    res.json({ stats });
  } catch (error) {
    logger.error('Get post stats error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// @route   GET /api/posts/failed/retry
// @desc    Get failed posts that can be retried
// @access  Private
router.get('/failed/retry', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const { maxRetries = 3 } = req.query;

    const posts = await postModel.getFailedPostsForRetry(userId, parseInt(maxRetries as string));

    res.json({ posts });
  } catch (error) {
    logger.error('Get failed posts error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

// @route   POST /api/posts/auto-schedule
// @desc    Auto-schedule posts for the next few days
// @access  Private
router.post('/auto-schedule', authenticateToken, async (req: Request, res: Response) => {
  try {
    const userId = (req as any).userId;
    const { days = 7, postsPerDay = 3 } = req.body;

    // This would integrate with the smart posting time algorithm
    // For now, we'll create a basic implementation
    const scheduledPosts = [];

    for (let day = 0; day < days; day++) {
      const date = new Date();
      date.setDate(date.getDate() + day);

      for (let post = 0; post < postsPerDay; post++) {
        // Get next video for posting
        const category = post % 2 === 0 ? 'real-estate' : 'cartoon';
        const video = await videoModel.getNextVideoForPosting(userId, category);

        if (video) {
          // Schedule post at default times (9am, 1pm, 6pm)
          const postingTimes = ['09:00', '13:00', '18:00'];
          const scheduledTime = new Date(date);
          const [hours, minutes] = postingTimes[post].split(':');
          scheduledTime.setHours(parseInt(hours), parseInt(minutes), 0, 0);

          const postData = {
            userId,
            videoId: video.id,
            platform: 'instagram',
            content: video.preferredCaption || `Check out this amazing ${video.category} content!`,
            hashtags: video.preferredHashtags || ['realestate', 'homes', 'property'],
            scheduledTime,
            autoGenerated: true,
            contentType: 'video',
            musicUsed: video.preferredMusic,
            thumbnailUsed: video.thumbnailPath,
          };

          const newPost = await postModel.create(postData);
          scheduledPosts.push(newPost);

          // Mark video as posted
          await videoModel.markAsPosted(video.id);
        }
      }
    }

    logger.info(`Auto-scheduled ${scheduledPosts.length} posts for user ${userId}`);

    res.json({
      message: `Auto-scheduled ${scheduledPosts.length} posts`,
      posts: scheduledPosts.map(post => ({
        id: post.id,
        videoId: post.videoId,
        scheduledTime: post.scheduledTime,
        status: post.status,
      })),
    });
  } catch (error) {
    logger.error('Auto-schedule posts error:', error);
    res.status(500).json({ error: 'Server error' });
  }
});

export default router; 