const { getDB } = require('../config/database');

class Post {
  static async create(postData) {
    const db = getDB();
    const { userId, videoId, platform, content, status, scheduledTime, autoGenerated, contentType } = postData;
    
    return new Promise((resolve, reject) => {
      db.run(
        'INSERT INTO posts (userId, videoId, platform, content, status, scheduledTime, autoGenerated, contentType) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
        [userId, videoId, platform, JSON.stringify(content), status, scheduledTime, autoGenerated ? 1 : 0, contentType || 'video'],
        function(err) {
          if (err) {
            reject(err);
          } else {
            resolve({ id: this.lastID, ...postData });
          }
        }
      );
    });
  }

  static async findById(id) {
    const db = getDB();
    
    return new Promise((resolve, reject) => {
      db.get(
        'SELECT * FROM posts WHERE id = ?',
        [id],
        (err, row) => {
          if (err) {
            reject(err);
          } else {
            if (row && row.content) {
              row.content = JSON.parse(row.content);
            }
            resolve(row);
          }
        }
      );
    });
  }

  static async findByUser(userId) {
    const db = getDB();
    
    return new Promise((resolve, reject) => {
      db.all(
        'SELECT * FROM posts WHERE userId = ? ORDER BY createdAt DESC',
        [userId],
        (err, rows) => {
          if (err) {
            reject(err);
          } else {
            rows.forEach(row => {
              if (row.content) {
                row.content = JSON.parse(row.content);
              }
            });
            resolve(rows);
          }
        }
      );
    });
  }

  static async updateStatus(id, status, result = null) {
    const db = getDB();
    
    return new Promise((resolve, reject) => {
      db.run(
        'UPDATE posts SET status = ?, postedTime = ? WHERE id = ?',
        [status, new Date().toISOString(), id],
        function(err) {
          if (err) {
            reject(err);
          } else {
            resolve({ changes: this.changes });
          }
        }
      );
    });
  }

  static async countByUser(userId) {
    const db = getDB();
    
    return new Promise((resolve, reject) => {
      db.get(
        'SELECT COUNT(*) as count FROM posts WHERE userId = ?',
        [userId],
        (err, row) => {
          if (err) {
            reject(err);
          } else {
            resolve(row.count);
          }
        }
      );
    });
  }
}

module.exports = Post; 